title:  Engin Bozkurt # your name (or website title) here
logo: "20190705_193719.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Electronics Engineer, Passionate lifelong learner and software developer
  <br><br>
  Machine Learning, Deep Learning, Data Science and Autonomous Driving Researcher
  <br><br>
  <a href="https://www.linkedin.com/in/enginbozkurteee/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
